### ISSUE TITLE
Transform defect point position

### ISSUE THREAD

**Issue by jdunkelmann** [ZEISS-PiWeb/PiWeb-Formplots#25]
Hi,
we need to extract all points from given defect plots and provide point positions in CAD coordinates. From how I understand the API description, <Geometry><Nominal><CoordinateSystem> along with the defect points' "real" position is what I need to perform the according calculations. Could you please provide me with the mathematical formula(s)? Thanks.

**Comment by Schnjan** [comment]
The header.xml contains a node 'ElementSystem' that contains a 4x4 matrix that describes the transformation Cad->Plot. To obtain the Cad positions, you need to calculate the inverse of that matrix and multiply the plot positions with it.
This works only, if the generating system of the pltx file provided a correct transformation matrix. Yout can verify this, by viewing the defects in the defect cad element.

**Comment by jdunkelmann** [comment]
Thanks Jan,
the header looks like this:
<Geometry Type="Defect">
  <Nominal>
    <CoordinateSystem>
      <Origin Z="-74.65" Y="-193.7412" X="-323.9356"/>
      <Axis1 Z="0" Y="0" X="3.3333333333333335"/>
      <Axis2 Z="0" Y="3.3333333333333335" X="0"/>
      <Axis3 Z="3.3333333333333335" Y="0" X="0"/>
    </CoordinateSystem>
    <Size Z="1061" Y="1293" X="2161"/>
  </Nominal>
  <Actual>
    <CoordinateSystem>
      ...
    </CoordinateSystem>
    <Size Z="1" Y="1" X="1"/>
  </Actual>
</Geometry>
I assume the nominal coordinate system refers to what you called "ElementSystem"?

> you need to calculate the inverse of that matrix and multiply the plot positions with it.
Not being familiar with 3d math, could you provide more details or even code on how to "invert" and "multiply" the matrix? Can this be found in one of the PiWeb APIs?

**Comment by jdunkelmann** [comment]
Thanks Jan.
The given defect plot header looks like this:
<Geometry Type="Defect">
  <Nominal>
    <CoordinateSystem>
      <Origin Z="-74.65" Y="-193.7412" X="-323.9356"/>
      <Axis1 Z="0" Y="0" X="3.3333333333333335"/>
      <Axis2 Z="0" Y="3.3333333333333335" X="0"/>
      <Axis3 Z="3.3333333333333335" Y="0" X="0"/>
    </CoordinateSystem>
    <Size Z="1061" Y="1293" X="2161"/>
  </Nominal>
  <Actual>
    <CoordinateSystem>
      <Origin Z="0" Y="0" X="0"/>
      <Axis1 Z="0" Y="0" X="1"/>
      <Axis2 Z="0" Y="1" X="0"/>
      <Axis3 Z="1" Y="0" X="0"/>
    </CoordinateSystem>
    <Size Z="1" Y="1" X="1"/>
  </Actual>
</Geometry>

I assume the nominal coordinate system refers to what you called ElementSystem?
Also, could you provide more details on how to "invert" and "multiply" matrixes? I am not very familiar with 3d vector math. Can the according code possibly be found in one of the PiWeb APIs?

**Comment by jdunkelmann** [comment]
Done. Thanks, Jan.
